---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-k8-development
  namespace: development
  labels:
    app: flask-backend-k8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-backend-k8
  template:
    metadata:
      labels:
        app: flask-backend-k8
    spec:
      containers:
        - name: pod-info-container
          image: joshbrusa/flask-backend-k8
          ports:
            - containerPort: 5000
