---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-k8-development-service
  namespace: development
spec:
  selector:
    app: flask-backend-k8
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
